apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-web-scraper
spec:
  selector:
    matchLabels:
      app: busybox-web-scraper
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox-web-scraper
    spec:
      containers:
        - name: busybox
          image: busybox
          command: [ "/bin/sh",  "-c",  "wget -qO- http://www.techsckool.com/ --no-check-certificate > techsckool.html; \
             sleep 600" ]