apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-web-scraper
spec:
  selector:
    matchLabels:
      app: busybox-web-scraper
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox-web-scraper
    spec:
      containers:
        - name: busybox
          image: busybox
          command: 
          - "/bin/sh"
          - "-c"
          - "while true; \
             do \
              SCRAPING_URL=`cat /tmp/SCRAPING_URL`; \
              FILENAME=`cat /tmp/FILENAME`; \
              echo received inputs: SCRAPING_URL : $SCRAPING_URL; \
              echo received inputs: FILENAME : $FILENAME; \
              wget -qO- $SCRAPING_URL --no-check-certificate > /tmp/output/$FILENAME; \
              sleep 10; \
             done"
          volumeMounts:
            - name: output-volume
              mountPath: /tmp/output
            - name: config
              mountPath: /tmp
          resources:
            requests:
              cpu: 2m
              memory: 5Mi
            limits:
              cpu: 20m
              memory: 20Mi
      volumes:
      - name:  output-volume
        emptyDir:
          sizeLimit: 500Mi
      - name: config
        configMap:
          name: demoapp
