apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: output-volume
      mountPath: /tmp/output
    resources: {}
  
  volumes:
  - name:  output-volume
    hostPath:
      path: /home
