apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demoapp
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-csi-premium
  
